#pragma once

#include "engine/Config.h"
#include "engine/system/platform/Window.h"
#include "engine/message/Message.h"

namespace ds_platform
{
class Video
{
public:
    /**
     * Initialize the video system.
     *
     * Creates a window with the default settings.
     *
     * @param   config  const Config &, configuration loaded by the engine.
     * @return          bool, TRUE if initialization succeeds, FALSE otherwise.
     */
    bool Initialize(const ds::Config &config);

    /**
     * Update the video system.
     *
     * Swaps the graphics buffers, clears the screen and updates the renderer.
     */
    void Update();

    /**
     * Shutdown the video system.
     */
    void Shutdown();

    /**
     * Collect messages generated by the video instance.
     *
     * @return  ds_msg::MessageStream, stream of messages generated by this
     * system.
     */
    ds_msg::MessageStream CollectMessages();

private:
    Window m_window;

    ds_msg::MessageStream m_messagesGenerated;
};
}
