* Git workflow
** Git basics

Create a new branch:
#+BEGIN_SRC shell
git branch <branch_name>
#+END_SRC

Switch branches:
#+BEGIN_SRC shell
git checkout <branch_name>
#+END_SRC

Create a new branch and switch to it:
#+BEGIN_SRC shell 
git checkout -b <branch_name>
#+END_SRC

Add some changes to the staging area:
#+BEGIN_SRC shell
git add <file_name(s)>
#+END_SRC

Commit changes in staging area (see git commit message conventions):
#+BEGIN_SRC shell
git commit
#+END_SRC

Push committed changes on your local branch to the <branch_name> on your repo:
! Note, 90% of the time you'll want <branch_name> to match your current branch name ! 
#+BEGIN_SRC shell
git push origin <branch_name>
#+END_SRC

See modified files, staged files and your current branch (very useful - use often):
#+BEGIN_SRC shell
git status
#+END_SRC

** General Git workflow

- Create a new branch for your new feature and move to it.

#+BEGIN_SRC shell
git checkout -b lphipps_newFeature
#+END_SRC

- Do some work...
- Add your work to the staging area.

#+BEGIN_SRC shell
git add file1 file2
#+END_SRC

- Commit your work.
#+BEGIN_SRC shell
git commit
#+END_SRC

- Push your work to your fork.

#+BEGIN_SRC shell
git push origin lphipps_newFeature
#+END_SRC

- Using the GitHub UI, submit a pull request against the **develop branch** on the master repo.

- Assign at least two other group members as reviewers.
