* User manual

Note that all paths are relative to the submission root directory (i.e. "./" is the submission root directory).

** Build instructions
- Navigate to the "./build"
- Open the Visual Studio 2013 solution file (theplastics.sln) present there.
- Right-click on each project in the solution (ds_math, drunkensailorengine then final) and choose "Build" or "Rebuild", this will output an executable file to "./executable/bin"

** Running the program
- Navigate to the ./executable directory.
- Double-click the final.exe to execute the project.
OR
- Open the Visual Studio 2013 solution file present in "./build/theplastics.sln"
- Right-click the "final" project and choose "Set as startup project".
- Click the "Green play button" at the top of the window or press 'F5' to run the project from Visual Studio 2013.

** Keybindings
- Use the w, a, s and d keys to move around
- Use the mouse to look around
- Use the spacebar to jump
- Use the escape key to quit. This will show a picture of the team's faces,
  press the left mouse button to actually quit.
