#pragma once

namespace ds_phys
{
class ContactResolver;

class Contact
{
    friend class ContactResolver;

public:
protected:
private:
};

class ContactResolver
{
};

class IContactGenerator
{
public:
    /**
     * Fills the contact array with contacts generated by the contact generator.
     * The contact pointer should point to the first available contact in the
     * contact array, where limit is the maximum number of contacts in the array
     * that can be written to. The method returns the number of contacts that
     * actually have been written to.
     *
     * @param   contact   Contact *, pointer to first contact in array.
     * @param   limit     unsigned int, size of the contact array.
     * @return            unsigned int, number of contacts that were actually
     *                    written to.
     */
    virtual unsigned int addContact(Contact *contact,
                                    unsigned int limit) const = 0;
};
}
